### ISSUE TITLE
Metric name changed, warnings and errors looking for `val_loss`.

### ISSUE THREAD

**Issue by mapio** [iomega/ms2query#212] opened 2023-11-20 11:28 UTC
Executing the example at https://github.com/iomega/ms2query#create-your-own-library-and-train-new-models the code emits a series of warnings

```
WARNING:tensorflow:Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: loss,mae,root_mean_squared_error
```

that can apparently fixed by replacing `val_loss` with `loss` at line 66 and 67 of `ms2query/create_new_library/train_ms2deepscore.py`. By doing so, though, the code halts at line 71 raising a file not found exception (is it normal that weights are loaded during model save?).

Commenting line 71 the code than halts at line 79 (again due to the absence of `val_loss` key in `history`).

**Comment by niekdejonge** [comment] 2023-11-21 11:29
Same response as to #214 
I was not yet able to reproduce your error.
I tried to reproduce it by running the test in https://github.com/iomega/ms2query/blob/main/tests/test_train_models.py
But this did run as expected for me.

What I now suspect, is that you have some dependency that is different from what I have locally, that makes the code crash. This might still be due to us setting the allowed versions too broadly. Can you maybe give an overview of your installed dependencies?

You could also check if all tests are running locally by running

pytest
Do all tests pass for you?

**Comment by niekdejonge** [comment] 2023-11-21 17:06
I suspect that this is the same issue as #214, I will therefore close it already, we can discuss further in #214

**Closed by niekdejonge** 2023-11-21 17:06 UTC
